---
- name: Deploy Apache web server on Ubuntu clients
  hosts: ubuntu-clients
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
    
    - name: Copy custom index.html
      copy:
        content: "<h1>Welcome to my Apache server!</h1>"
        dest: /var/www/html/index.html

    - name: Start and enable Apache service
      systemd:
        name: apache2
        state: started
        enabled: yes

- name: Install Git on all Ubuntu clients
  hosts: ubuntu-clients
  become: yes
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

- name: Display my name on all hosts
  hosts: all
  vars:
    my_name: "Sadate Moustapha"
  tasks:
    - name: Show my name
      debug:
        msg: "Hello, my name is {{ my_name }}"
